[g07n18:84589] *** Process received signal ***
[g07n18:84589] Signal: Segmentation fault (11)
[g07n18:84589] Signal code: Address not mapped (1)
[g07n18:84589] Failing at address: 0xb0
[g07n18:84589] [ 0] [g07n18:84590] *** Process received signal ***
[g07n18:84590] Signal: Segmentation fault (11)
[g07n18:84590] Signal code: Address not mapped (1)
[g07n18:84590] Failing at address: 0xb0
[g07n18:84590] [ 0] [0x2000000504d8]
[g07n18:84589] [ 1] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(darshan_core_lookup_record_name+0x38)[0x200000078b18]
[g07n18:84589] [ 2] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(darshan_posix_lookup_record_name+0x6c)[0x200000088a4c]
[g07n18:84589] [ 3] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(fdopen+0x9c)[0x2000000963fc]
[g07n18:84589] [0x2000000504d8]
[g07n18:84590] [ 1] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(darshan_core_lookup_record_name+0x38)[0x200000078b18]
[g07n18:84590] [ 2] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(darshan_posix_lookup_record_name+0x6c)[0x200000088a4c]
[g07n18:84590] [ 3] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(fdopen+0x9c)[0x2000000963fc]
[g07n18:84590] [ 4] [ 4] python(PyTokenizer_FindEncodingFilename+0x5c)[0x13335a01c]
[g07n18:84589] [ 5] python(_Py_DisplaySourceLine+0xe4)[0x133205694]
[g07n18:84589] [ 6] python(PyTraceBack_Print+0x254)[0x13339afa4]
[g07n18:84589] [ 7] python(PyTokenizer_FindEncodingFilename+0x5c)[0x13ef2a01c]
[g07n18:84590] [ 5] python(_Py_DisplaySourceLine+0xe4)[0x13edd5694]
[g07n18:84590] [ 6] python(PyTraceBack_Print+0x254)[0x13ef6afa4]
[g07n18:84590] [ 7] python(+0x2172a4)[0x13ef272a4]
[g07n18:84590] [ 8] python(PyErr_Display+0xcc)[0x13ef27fdc]
[g07n18:84590] [ 9] python(+0x2ac870)[0x13efbc870]
[g07n18:84590] python(+0x2172a4)[0x1333572a4]
[g07n18:84589] [ 8] python(PyErr_Display+0xcc)[0x133357fdc]
[g07n18:84589] [ 9] python(+0x2ac870)[0x1333ec870]
[g07n18:84589] [10] python(_PyCFunction_FastCallDict+0xb0)[0x133214cb0]
[g07n18:84589] [11] [10] python(_PyCFunction_FastCallDict+0xb0)[0x13ede4cb0]
[g07n18:84590] [11] python(_PyObject_FastCallDict+0x35c)[0x13ede537c]
[g07n18:84590] [12] python(PyErr_PrintEx+0x14c)[0x13efb7cbc]
[g07n18:84590] [13] python(PyErr_Print+0x1c)[0x13efb801c]
[g07n18:84590] [14] python(_PyObject_FastCallDict+0x35c)[0x13321537c]
[g07n18:84589] [12] python(PyErr_PrintEx+0x14c)[0x1333e7cbc]
[g07n18:84589] [13] python(PyErr_Print+0x1c)[0x1333e801c]
[g07n18:84589] [14] python(PyRun_SimpleFileExFlags+0x334)[0x1333f5334]
[g07n18:84589] [15] python(PyRun_AnyFileExFlags+0x64)[0x1333f5714]
[g07n18:84589] [16] python(PyRun_SimpleFileExFlags+0x334)[0x13efc5334]
[g07n18:84590] [15] python(PyRun_AnyFileExFlags+0x64)[0x13efc5714]
[g07n18:84590] [16] python(Py_Main+0xa88)[0x13efcc238]
[g07n18:84590] [17] python(Py_Main+0xa88)[0x1333fc238]
[g07n18:84589] [17] python(main+0x140)[0x1331cb280]
[g07n18:84589] [18] /lib64/libc.so.6(+0x25200)[0x200000165200]
[g07n18:84589] [19] python(main+0x140)[0x13ed9b280]
[g07n18:84590] [18] /lib64/libc.so.6(+0x25200)[0x200000165200]
[g07n18:84590] [19] /lib64/libc.so.6(__libc_start_main+0xc4)[0x2000001653f4]
[g07n18:84590] *** End of error message ***
/lib64/libc.so.6(__libc_start_main+0xc4)[0x2000001653f4]
[g07n18:84589] *** End of error message ***
[g06n17:122886] *** Process received signal ***
[g06n17:122886] Signal: Segmentation fault (11)
[g06n17:122886] Signal code: Address not mapped (1)
[g06n17:122886] Failing at address: 0xb0
[g06n17:122886] [ 0] [0x2000000504d8]
[g06n17:122886] [ 1] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(darshan_core_lookup_record_name+0x38)[0x200000078b18]
[g06n17:122886] [ 2] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(darshan_posix_lookup_record_name+0x6c)[0x200000088a4c]
[g06n17:122886] [ 3] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(fdopen+0x9c)[0x2000000963fc]
[g06n17:122886] [ 4] python(PyTokenizer_FindEncodingFilename+0x5c)[0x108eca01c]
[g06n17:122886] [ 5] python(_Py_DisplaySourceLine+0xe4)[0x108d75694]
[g06n17:122886] [ 6] python(PyTraceBack_Print+0x254)[0x108f0afa4]
[g06n17:122886] [ 7] python(+0x2172a4)[0x108ec72a4]
[g06n17:122886] [ 8] python(PyErr_Display+0xcc)[0x108ec7fdc]
[g06n17:122886] [ 9] python(+0x2ac870)[0x108f5c870]
[g06n17:122886] [10] python(_PyCFunction_FastCallDict+0xb0)[0x108d84cb0]
[g06n17:122886] [11] python(_PyObject_FastCallDict+0x35c)[0x108d8537c]
[g06n17:122886] [12] python(PyErr_PrintEx+0x14c)[0x108f57cbc]
[g06n17:122886] [13] python(PyErr_Print+0x1c)[0x108f5801c]
[g06n17:122886] [14] python(PyRun_SimpleFileExFlags+0x334)[0x108f65334]
[g06n17:122886] [15] python(PyRun_AnyFileExFlags+0x64)[0x108f65714]
[g06n17:122886] [16] python(Py_Main+0xa88)[0x108f6c238]
[g06n17:122886] [17] python(main+0x140)[0x108d3b280]
[g06n17:122886] [18] /lib64/libc.so.6(+0x25200)[0x200000165200]
[g06n17:122886] [19] /lib64/libc.so.6(__libc_start_main+0xc4)[0x2000001653f4]
[g06n17:122886] *** End of error message ***
[g06n17:122882] *** Process received signal ***
[g06n17:122882] Signal: Segmentation fault (11)
[g06n17:122882] Signal code: Address not mapped (1)
[g06n17:122882] Failing at address: 0xb0
[g06n17:122882] [ 0] [0x2000000504d8]
[g06n17:122882] [ 1] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(darshan_core_lookup_record_name+0x38)[0x200000078b18]
[g06n17:122882] [ 2] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(darshan_posix_lookup_record_name+0x6c)[0x200000088a4c]
[g06n17:122882] [ 3] /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/darshan-runtime-3.1.7-cnvxicgf5j4ap64qi6v5gxp67hmrjz43/lib/libdarshan.so(fdopen+0x9c)[0x2000000963fc]
[g06n17:122882] [ 4] python(PyTokenizer_FindEncodingFilename+0x5c)[0x121b2a01c]
[g06n17:122882] [ 5] python(_Py_DisplaySourceLine+0xe4)[0x1219d5694]
[g06n17:122882] [ 6] python(PyTraceBack_Print+0x254)[0x121b6afa4]
[g06n17:122882] [ 7] python(+0x2172a4)[0x121b272a4]
[g06n17:122882] [ 8] python(PyErr_Display+0xcc)[0x121b27fdc]
[g06n17:122882] [ 9] python(+0x2ac870)[0x121bbc870]
[g06n17:122882] [10] python(_PyCFunction_FastCallDict+0xb0)[0x1219e4cb0]
[g06n17:122882] [11] python(_PyObject_FastCallDict+0x35c)[0x1219e537c]
[g06n17:122882] [12] python(PyErr_PrintEx+0x14c)[0x121bb7cbc]
[g06n17:122882] [13] python(PyErr_Print+0x1c)[0x121bb801c]
[g06n17:122882] [14] python(PyRun_SimpleFileExFlags+0x334)[0x121bc5334]
[g06n17:122882] [15] python(PyRun_AnyFileExFlags+0x64)[0x121bc5714]
[g06n17:122882] [16] python(Py_Main+0xa88)[0x121bcc238]
[g06n17:122882] [17] python(main+0x140)[0x12199b280]
[g06n17:122882] [18] /lib64/libc.so.6(+0x25200)[0x200000165200]
[g06n17:122882] [19] /lib64/libc.so.6(__libc_start_main+0xc4)[0x2000001653f4]
[g06n17:122882] *** End of error message ***
ERROR:  One or more process (first noticed rank 7) terminated with signal 11 (core dumped)

------------------------------------------------------------
Sender: LSF System <lsfadmin@batch5>
Subject: Job 374429: <bert_synth> in cluster <summit> Exited

Job <bert_synth> was submitted from host <login5> by user <yngtodd> in cluster <summit> at Mon Sep 28 20:15:49 2020
Job was executed on host(s) <1*batch5>, in queue <batch>, as user <yngtodd> in cluster <summit> at Mon Sep 28 20:16:34 2020
                            <42*g06n17>
                            <42*g07n18>
</ccs/home/yngtodd> was used as the home directory.
</gpfs/alpine/proj-shared/med107/yngtodd/src/Benchmarks/Pilot3/P3B6> was used as the working directory.
Started at Mon Sep 28 20:16:34 2020
Terminated at Mon Sep 28 20:18:11 2020
Results reported at Mon Sep 28 20:18:11 2020

The output (if any) is above this job summary.

